# Generated by Django 3.0.7 on 2020-10-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
