# Generated by Django 3.0.7 on 2020-10-31 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0003_expenses_is_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='name',
        ),
    ]
