# Generated by Django 3.0.7 on 2020-10-31 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0004_remove_expenses_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='quantity',
        ),
    ]
