# Generated by Django 3.0.7 on 2020-11-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0005_remove_expenses_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
