# Generated by Django 3.0.7 on 2020-11-03 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0007_auto_20201103_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenue',
            name='slug',
        ),
    ]
