# Generated by Django 3.0.7 on 2020-11-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0009_remove_expenses_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, max_length=9),
        ),
    ]
