# Generated by Django 3.0.7 on 2020-11-04 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d/%S')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True, help_text='Checked means the stock is ready for sales')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('vendor_phone', models.CharField(blank=True, max_length=20)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('vendor_email', models.EmailField(blank=True, max_length=254)),
                ('vendor_website', models.URLField(blank=True)),
                ('stock_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=11, max_length=9)),
                ('transport_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=11, max_length=9)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='shop.Category')),
                ('sold_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='saler', to=settings.AUTH_USER_MODEL)),
                ('stock_updated_by', models.ManyToManyField(blank=True, related_name='updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
