# Generated by Django 3.0.7 on 2020-11-04 06:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='initial_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_updated_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='updater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='transport_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
