# Generated by Django 3.0.7 on 2020-10-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='serial_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='transport_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.CharField(default='hu', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_email',
            field=models.EmailField(default='rama@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_phone',
            field=models.CharField(default='09090', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_website',
            field=models.URLField(default='kk'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='expiry_date',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
